DEFRA/adp-infrastructure-core

.azuredevops/deploy-platform-core.yaml, infra/front-door/front-door.bicep, infra/front-door/front-door.parameters.json
Created bicep template and associated parameter file
Added the template for Azure Front Door deployment in the deploy-platform-core.yaml file
Updated Front Door registry module
Removed the 'Standard_AzureFrontDoor' option from sku
Link to the relevant work items: e.g. [AB#214106](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/214106)
[[AB#214807](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/214807)] 
Testing as already setup within the ADO pipeline runs.
=> 214106: Azure Front Door Update

infra/managed-cluster/aks-cluster.bicep, infra/managed-cluster/aks-cluster.parameters.json
Added monitoring container insight/workspace for AKS Cluster 
[AB#195075](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/195075)
Confirmed that it is enabled on portal
No conflict with deployment as error on AKS cluster in pipeline resolved
=> 195075: Enable container insight on AKS cluster

.azuredevops/deploy-platform-core.yaml, infra/managed-cluster/.bicep/acr-pull.bicep, infra/managed-cluster/aks-cluster.bicep, infra/managed-cluster/aks-cluster.parameters.json, infra/network/subnet-nsg.parameters.json, infra/network/virtual-network.parameters.json
Install internal loadbalancer and change the outbound traffic to UDR.
[AB#223150](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/223150)
Successfully deployment with the pipeline.
=> 223150: AKS Internal Loadbalancer

infra/core/managed-cluster/aks-cluster.bicep
Enable image-automation-controller and image-reflector-controller on AKS cluster
AB#240172
Ran test pipeline for AKS cluster and confirmed settings enabled on Azure portal.*
=> 223622: Deploy Demo Service using GitOps - Enable fluxExtension

.azuredevops/deploy-platform-core.yaml, infra/core/managed-cluster/aks-cluster.bicep, infra/core/managed-cluster/aks-cluster.parameters.json, infra/core/observability/azure-monitor-workspace.bicep, infra/core/observability/azure-monitor-workspace.parameters.json, infra/core/scripts/Get-WorkspaceResourceIds.ps1
Moved Grafana deployment to monitor
Created a new bicep template for Azure Monitor Workspace. 
[AB#231059](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/231059)
Tested with the core pipeline.
=> 231059:Move Grafana to monitor group

.azuredevops/deploy-platform-core.yaml, infra/core/public-dns-zone/dns-zone.bicep, infra/core/public-dns-zone/dns-zone.parameters.json
Added Public Dns zone resource
[AB#214100](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/214100)
[![Build Status](https://dev.azure.com/defragovuk/DEFRA-FFC/_apis/build/status%2FADP%2FCore%2Fplatform-adp-core?repoName=DEFRA%2Fadp-infrastructure&branchName=pp%2Fadp-dns-zone)](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/latest?definitionId=4407&repoName=DEFRA%2Fadp-infrastructure&branchName=pp%2Fadp-dns-zone)
=> 214100: Adp Dns zone

.azuredevops/deploy-platform-core.yaml, bicepconfig.json, infra/core/front-door/front-door.bicep, infra/core/front-door/front-door.parameters.json, infra/core/operational-insights/workspace.bicep, infra/core/public-dns-zone/dns-zone.bicep
Added  FrontDoor endpoint for AKS cluster
[AB#231044](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/231044)
[![Build Status](https://dev.azure.com/defragovuk/DEFRA-FFC/_apis/build/status%2FADP%2FCore%2Fplatform-adp-core?repoName=DEFRA%2Fadp-infrastructure&branchName=pp%2Ffront-door-endpoint)](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/latest?definitionId=4407&repoName=DEFRA%2Fadp-infrastructure&branchName=pp%2Ffront-door-endpoint)
=> 231044: AKS FrontDoor Endpoint

pull_request_template.md
I am improving the PR template to add more context, and make it more fun..  Links to  [AB#248404](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/248404)
I have added a giphy 
N/A here!
=> 248404: Update the Pull Request Template

.azuredevops/deploy-platform-bootstrap.yaml, .azuredevops/deploy-platform-core-shared-services.yaml, .azuredevops/deploy-platform-core.yaml, infra/core/front-door/front-door.parameters.json
Update YAML pipelines to use the latest common pipeline.
[AB#231044](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/231044)
[![Build Status](https://dev.azure.com/defragovuk/DEFRA-FFC/_apis/build/status%2FADP%2FBootstrap%2Fplatform-adp-bootstrap?repoName=DEFRA%2Fadp-infrastructure-core&branchName=pp%2Fuse-new-varaibles)](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/latest?definitionId=4347&repoName=DEFRA%2Fadp-infrastructure-core&branchName=pp%2Fuse-new-varaibles)
[![Build Status](https://dev.azure.com/defragovuk/DEFRA-FFC/_apis/build/status%2FADP%2FCore%2Fplatform-adp-core?repoName=DEFRA%2Fadp-infrastructure-core&branchName=pp%2Fuse-new-varaibles)](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/latest?definitionId=4407&repoName=DEFRA%2Fadp-in …
=> 231044: Update YAML Pipelines

infra/core/key-vault/application-key-vault.bicep, infra/core/key-vault/application-key-vault.parameters.json
* Added Keyvault secret office role to service connection*
*Link to the relevant work items: e.g. [AB#245827](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/245827)*
- [x ] Story Work items associated (not Tasks)
- [ x] Successful testing run(s) link provided
- [ x] Title pattern should be `{work item number}: {title}`
- [ x] Description covers all the changes in the PR
=> 245827: Assign Key Vault Secrets Officer role

.azuredevops/deploy-platform-bootstrap.yaml, .azuredevops/deploy-platform-core.yaml, infra/common/network/virtual-network.parameters.json, infra/core/postgre-sql/flexible-server.bicep, infra/core/postgre-sql/flexible-server.parameters.json, infra/core/private-dns-zone/aks-cluster-zone.bicep, infra/core/private-dns-zone/flexible-server-zone.bicep, infra/core/private-dns-zone/flexible-server-zone.parameters.json
Creates a new Private DNS and links it to the PostgreSQL server. 
[![Build Status](https://dev.azure.com/defragovuk/DEFRA-FFC/_apis/build/status%2FADP%2FCore%2Fplatform-adp-core?repoName=DEFRA%2Fadp-infrastructure-core&branchName=pp%2Fflexible-server-zone)](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/latest?definitionId=4407&repoName=DEFRA%2Fadp-infrastructure-core&branchName=pp%2Fflexible-server-zone)
=> 232785: Flexible Server DNS zone

infra/core/managed-cluster/aks-cluster.bicep
Correct the cluster and agent pool properties to support the version upgrades.
Update to the agent pool names as per the latest design.
Link to the relevant work items: [AB#249140](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/249140)
None
n/a
=> 249140: Agent Pool rename and properties changes

infra/core/managed-cluster/aks-cluster.bicep
Added Ingress label for the system node pool
[AB#249140](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/249140)
=> 249140: Add node label for Ingress

README.md
I am updating the ADO Infra Project Wiki to improve readability and useability. More documentation should be added later to detail the modules.
We need to continue to update this Wiki on each PR.
=> Update Project Wiki

infra/core/app-configuration/config-data/config-data.json
Fixed config data value variables replace format.
[AB#249140](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/249140)
=> 249140:Fix config data

.azuredevops/deploy-platform-bootstrap.yaml, infra/bootstrap/scripts/Trigger-VNetPeering.ps1
Add step to trigger the CCOE Pipeline for linking the ADP environment spoke VNet to the Hub VNets.
Relates to ADO Work Item [AB#209535](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/209535) and builds on [#398319](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=398319&view=results)
N/A
Tested the CCOE pipeline triggered from ADP.
=> 209535: Trigger VNET linking to Hub

infra/core/app-configuration/config-data/config-data.json, infra/core/managed-cluster/aks-cluster.bicepparam, infra/core/redis-cache/redis-cache.parameters.json
App config setting added CLUSTER_NAME key. 
Updated Redis firewall to allow user node pool.
=> 262177: App config setting & Redis firewall 

.azuredevops/deploy-platform-core.yaml, infra/core/app-configuration/config-data/config-data.json
Renamed Platform label to adp-platform
[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177) 
=> 262177 : Rename Platform label to adp-platform

README.md
=> DR: Add Build Status Badge

infra/bootstrap/config/app-registrations/tier2-app-registration.json
Add object id of the App Reg SPN to the key vault.
Relates to ADO Work Item [AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)
N/A
N/A
=> 262177: Add SPN ObjectId to the KV

.azuredevops/deploy-platform-core-env-tenant.yaml
Refer Pipeline common from main branch.
[AB#267512](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/267512)
=> 267512:Refer from main branch

.azuredevops/deploy-platform-bootstrap-env.yaml, .azuredevops/deploy-platform-build-agent.yaml, .azuredevops/deploy-platform-core-env-shared.yaml, .azuredevops/publish-platform-nginxplus.yaml, infra/build-agent/Create-AdoBuildAgent.ps1
Added DEV1 and SSV5 envs to the pipelines
Relates to ADO Work Item [AB#259849](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259849)
=> 259849: Added DEV1 and SSV5 envs to the pipelines

.azuredevops/publish-platform-nginxplus.yaml
NGINX pipeline Migrated to infra template. 
[AB#261316](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/261316)
=> 261316: Use infra template in Nginx pipeline

infra/core/env/front-door/azure-waf.parameters.json
Removed WAF custom rule.
[AB#267512](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/267512)
=> 267512:Remove Custom rule

.azuredevops/deploy-platform-core-env.yaml
SSH Keys change variable to use ssv SubscriptionId 
[AB#267512](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/267512)
=> 267512:SSH Keys change variable to use ssvSubscriptionId

.azuredevops/deploy-platform-core-env-tenant.yaml
Use SSV5 service connections for defra tenant.
[AB#267512](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/267512)
=> 267512: Use SSV5

.azuredevops/deploy-platform-build-agent.yaml
TST build agent environment. 
[AB#261316](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/261316)
=> 261316:TST build agent environment

.azuredevops/publish-powershell-docker-image.yaml, .vscode/settings.json, powershell-executor/powershell-executor.Dockerfile
This PR contains the changes to add dockerfile to execute powershell scripts inside container and pipeline to publish image
*[AB#267988](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/267988)*
=> 267988: Added dockerfile to execute powershell scripts inside container and pipeline to publish image

.azuredevops/deploy-platform-bootstrap-env.yaml, .azuredevops/deploy-platform-build-agent.yaml
This PR is to add PRE and PRD to DevOps pipelines now that we are ready to deploy to PRE.
[AB#259850](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259850)
AB#296718
Flux configurations have been tested in all lower environments successfully.
=> 293718: Add Pre and Prd stages to pipelines

.azuredevops/deploy-platform-core-portal.yaml
[AB#249199](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/249199)
Re ordered the portal app infra deployment as storage deployment needs keyvault
=> 249199: SSV5 Deployment fix

.azuredevops/deploy-platform-core-portal.yaml, infra/core/env-shared/network/virtual-network.bicep, infra/core/env-shared/portal/container-apps-env/.bicep/set-secret.bicep, infra/core/env-shared/portal/container-apps-env/container-apps-env.bicep, infra/core/env-shared/portal/container-apps-env/container-apps-env.bicepparam, infra/core/env-shared/portal/flexible-server/flexible-server.bicep
AB#241999
1. Removed Delete Lock from VNet as it is blocking Postgres DB deployment
2. Created module to deploy secret to shared keyvault
=> 249199 : Deploymentfix

.azuredevops/deploy-platform-build-agent.yaml
This PR is to add PRE to DevOps pipelines now that we are ready to deploy to PRE.
[AB#259850](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259850)
AB#296718
Flux configurations have been tested in all lower environments successfully.
=> 293718: Add Pre stages to pipelines

infra/core/env-shared/portal/container-apps-env/.bicep/set-secret.bicep, infra/core/env-shared/portal/container-apps-env/container-apps-env.bicep, infra/core/env-shared/portal/container-apps-env/container-apps-env.bicepparam
[AB#249199](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/249199) 
Refactored child resource parameter to avoid arm ttk validation issue
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=449519&view=logs&j=6060e638-0e23-5a0d-4ca0-764e21467523&t=7491cb5b-6245-5257-f4ba-6145373465dd
=> 249199: Fix for arm ttk validation

infra/core/env/front-door/front-door.bicep, infra/core/env/front-door/front-door.parameters.json
Added RuleSet to the Front door. This will be global ruleset that will be added to route of every service.
Relates to ADO Work Item [AB#287384](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/287384)
There will be changes in 'ADP-INFRASTRUCTURE-SERVICES' to link this ruleset to the service routes.
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=452128&view=logs&j=c0c82bbe-3d3c-5956-2f00-4f30d4a2d1a5&t=0148914e-d9f0-5a5e-0e4e-e3e5ba6334a9
=> 287384: HSTS header ruleset

.azuredevops/deploy-platform-core-env.yaml, infra/core/env/front-door/azure-waf.bicep, infra/core/env/front-door/azure-waf.parameters.json, infra/core/env/front-door/front-door.parameters.json
All changes related to moving FrontDoor instance to SEC subscription from ADP.
Relates to ADO Work Item [AB#296203](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/296203)
N/A
N/A
=> Changes related to FrontDoor move to SEC

infra/core/env/front-door/front-door.bicep, infra/core/env/front-door/front-door.parameters.json
Update the AFD template to set up endpoint for portal.
Relates to ADO Work Item [AB#296203](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/296203)
N/A
N/A
=> Add portal endpoint to the FrontDoor

infra/common/network/virtual-network.parameters.json
Added new Subnet for Service's Private endpoints
Relates to ADO Work Item [AB#306948](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/306948)
=> 306948: Added new Subnet for Service's Private endpoints

infra/core/env/app-configuration/config-data/config-data.json
This PR contains the changes to add platform vars for PRIVATE_ENDPOINT_PREFIX 
Relates to ADO Work Item [AB#306948](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/306948)
=> 306948: Added PRIVATE_ENDPOINT_PREFIX variable

flux-templates/templates/programme/team/base/helm-repository.yaml, flux-templates/templates/programme/team/base/patch/kustomize.yaml, flux-templates/templates/programme/team/service/deploy-kustomize.yaml, flux-templates/templates/programme/team/service/deploy/base/helm-release.yaml, flux-templates/templates/programme/team/service/infra-kustomize.yaml, flux-templates/templates/programme/team/service/infra/base/aso-helm-release.yaml, flux-templates/templates/programme/team/service/infra/base/image-repository.yaml, flux-templates/templates/programme/team/service/infra/environment/image-policy.yaml, flux-templates/templates/programme/team/service/pre-deploy-kustomize.yaml, flux-templates/templates/programme/team/service/pre-deploy/migration-kustomize.yaml, flux-templates/templates/programme/team/service/pre-deploy/migration/base/image-repository-dbmigration.yaml, flux-templates/templates/programme/team/service/pre-deploy/migration/base/migration.job.yaml, flux-templates/templates/programme/team/service/pre-deploy/migration/environment/image-policy.yaml, flux-templates/templates/programme/team/service/pre-deploy/post-migration-kustomize.yaml, flux-templates/templates/programme/team/service/pre-deploy/post-migration/base/post-migration-script.job.yaml, flux-templates/templates/programme/team/service/pre-deploy/pre-migration-kustomize.yaml, flux-templates/templates/programme/team/service/pre-deploy/pre-migration/base/pre-migration-script.job.yaml
This PR contains backstage labels added to flux manifest automation
=> 308026: Add backstage labels to flux manifest automation

infra/core/env/app-configuration/config-data/config-data.json, infra/core/env/managed-cluster/aks-cluster.bicep, infra/core/env/managed-cluster/aks-cluster.bicepparam
Enabled AKS Custom CA on node pools and added config for the secret.
[AB#261145](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/261145)
=> AKS Enable Custom ca trust

.azuredevops/deploy-platform-core-env.yaml
Redeploy Front Door instance to the ADP subscription.
Relates to ADO Work Item [AB#296203](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/296203)
N/A
N/A
=> Move AFD back to ADP subscription.

infra/core/env/managed-cluster/.bicep/keyvault-secret-rbac.bicep, infra/core/env/managed-cluster/aks-cluster.bicep, infra/core/env/managed-cluster/aks-cluster.bicepparam
Firewall secret role assignment.
[AB#261145](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/261145)
=> FW secret RBAC

infra/core/env/app-configuration/config-data/config-data.json
Added STORAGEACCOUNT_PREFIX variable require to build storage account name
Relates to ADO Work Item [AB#306948](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/306948)
=> 306948: Added STORAGEACCOUNT_PREFIX

infra/core/env/scripts/SSH-Generate-Keys.ps1
Removed quotes from SSH Keygen command. 
[AB#319699](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/319699)
=> Fix SSH Key Gen Issue

flux-templates/scripts/New-FluxServices.ps1, flux-templates/templates/programme/team/service/infra/environment/patch-backend.yaml, flux-templates/templates/programme/team/service/infra/environment/patch.yaml
Added STORAGEACCOUNT_PREFIX variable in Patch file
Relates to ADO Work Item [AB#306948](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/306948)
=> 306948: Added STORAGEACCOUNT_PREFIX variable in Patch file

.azuredevops/deploy-platform-core-portal.yaml, infra/core/env-shared/portal/app-registrations/portal-app-registration.json
*Link to the relevant work items: 
[AB#326088](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/326088) 
This PR adds localhost redirect uri for ssv3 app-reg only
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=487671&view=results
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.
=> 326088 : Add localhost to ssv3 app-reg only

flux-templates/scripts/New-FluxServices.ps1
Database name should have team name as prefix.
Relates to ADO Work Item [AB#326112](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/326112)
=> 326112: Database name should have team name as prefix.

scripts/modules/aad-groups/aad-groups.psm1
This PR contains the changes to add function to update an AD group with serviceprincipal as member.
[AB#307513](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/307513)
=> 307513: Added function to update an AD group with serviceprincipal as members

infra/core/env/postgre-sql/.bicep/kv-secret-role-secrets-user.bicep, infra/core/env/postgre-sql/flexible-server.bicep, infra/core/env/postgre-sql/flexible-server.bicepparam
Added RBAC for DB AAD MI to retrieve keyvault secrets
[AB#337888](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/337888)
=> 337888: Added RBAC for DB AAD MI to retrieve keyvault secrets

.azuredevops/deploy-platform-core-portal.yaml, infra/bootstrap/env/scripts/Trigger-VNetPeering.ps1
*Link to the relevant work items:*
[AB#344253](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/344253)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=518388&view=logs&j=e4f19080-647d-54ae-7293-f102a48b88af&t=f6b01c04-6b60-52fb-b5fa-f4cadf5c54a0
=> 344253: SSV to Sec vnet peering

.azuredevops/deploy-platform-core-env.yaml
Fix the conditions in pipeline to include monitoring job
N/A
N/A
=> Fix the monitoring job condition.

.azuredevops/deploy-platform-core-fluxnotification.yaml, infra/core/env-shared/flux-notification-apis/managed-identity/adocallbackapp-managed-identity.bicep, infra/core/env-shared/flux-notification-apis/managed-identity/adocallbackapp-managed-identity.bicepparam, infra/core/env-shared/flux-notification-apis/managed-identity/fluxnotificationapp-managed-identity.bicep, infra/core/env-shared/flux-notification-apis/managed-identity/fluxnotificationapp-managed-identity.bicepparam
Notification Api Baseline Infra : Created two Manage Identities required for 2 apps - Notification Api, CallBack Api
Relates to ADO Work Item [AB#333875](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/333875)
[*Any relevant testing information and pipeline runs.*](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=521725&view=logs&s=16aa9ed1-8f5e-5225-5bf7-0d2b8e07786b)
=> 333875: Notification Api Baseline Infra two Manage Identities

infra/bootstrap/env-shared/key-vault/platform-key-vault.parameters.json, infra/core/env-shared/portal/key-vault/key-vault.bicep, infra/core/env-shared/portal/key-vault/key-vault.bicepparam, infra/core/env/key-vault/application-keyvault-params/key-vault.bicepparam, infra/core/env/key-vault/key-vault.bicep, infra/core/env/key-vault/platform-keyvault-params/key-vault.bicepparam, infra/core/env/managed-cluster/.bicep/cluster-rbac.bicep, infra/core/env/managed-cluster/aks-cluster.bicep
Add Reader roles for Cluster and Key Vault for Platform Users Group
N/A
N/A
=> Add Reader roles for Cluster and Key Vault for Platform Users Group

.azuredevops/deploy-platform-sec-env.yaml
Comment out PRD stage in SEC pipeline
[AB#355292](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/355292)
=> 355292: Rename ssv shared env resources

.azuredevops/deploy-platform-sec-env.yaml
Enabled PRD enviroment for SEC resources pipeline
[AB#259852](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259852)
=> 259852:Enable PRD env for SEC resources

.azuredevops/deploy-platform-core-env.yaml, infra/core/env/scripts/Add-SshKeyToGitHubRepo.ps1, infra/core/env/scripts/SSH-Generate-Keys.ps1
Automate the Deploy Keys in Github flux services repo for each environment
Relates to ADO Work Item [AB#342305](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/342305)
N/A
N/A
=> 342305: Automate the Deploy Keys in Github flux services repo for each environment

.azuredevops/deploy-platform-core-tenant.yaml, infra/core/tenant/role-definition/cluster-custom-resources-reader-role.bicep, infra/core/tenant/role-definition/cluster-custom-resources-reader-role.parameters.json
[AB#369687](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/369687)
depend on 
https://github.com/DEFRA/adp-pipeline-common/pull/179
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=541531&view=results
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.
=> 369687 : Custom Role to read cluster

infra/core/iam/subscription/cluster-custom-resources-reader-role.bicep
[AB#372068](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/372068)
Added default values to resolve whatif scenario
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=550718&view=results
=> 372068: Automate Role Assignment

.azuredevops/deploy-platform-bootstrap-env-shared.yaml, infra/common/monitoring-insights/monitoring-insights.bicep, infra/common/monitoring-insights/monitoring-insights.bicepparam
*Link to the relevant work items:*
[AB#371158](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/371158)
App Insight resource added to shared subscription using existing log analytics workspace
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=552892&view=results
=> 371158: monitoring insigts resource in shared subscription

.gitignore, infra/core/env/managed-cluster/aks-cluster.bicep
Enable CSI driver on cluster for disk and file.
Relates to ADO Work Item [AB#383590](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/383590)
N/A
N/A
=> 383590: Enable CSI driver for Disk and File.

.azuredevops/deploy-platform-core-env.yaml, .azuredevops/deploy-platform-core-iam.yaml, infra/core/env/insights/aad-groups/monitoringpublishergroup.json, infra/core/iam/subscription/aad-groups/accessgroups.snd1.json, infra/core/iam/subscription/aad-groups/clusteraccessgroup.json
[AB#337878](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/337878)
Updated group creation process using common powershell
Added group owners for Monitoring publisher group used by App Insight and Cluster Custom Resource Reader used to provide access to teams
Updated group name since the existing groups cannot be updated.
Depends on PR: https://github.com/DEFRA/adp-pipeline-common/pull/206
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=572161&view=results
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=572191&view=results
Have you updated …
=> 337878: Updated group with owners

.azuredevops/deploy-platform-bootstrap-tenant.yaml, infra/bootstrap/tenant/scripts/Create-AADGroups.ps1, scripts/modules/aad-groups/aad-groups.psm1
[AB#389987](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/389987)
Fixed by using shared agents instead of default agents of Azure pipeline
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=573079&view=results
=> 389987: Fix for bootstrap tenant pipeline

infra/core/env/front-door/front-door-waf.bicep
[AB#374060](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/374060)
Allow the WAF to deploy in Production environment
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=577627&view=results
- [x ] Story Work items associated (not Tasks)
- [x ] Successful testing run(s) link provided
- [x ] Title pattern should be `{work item number}: {title}` 
- [x ] Description covers all the changes in the PR
=> 374060: Add IP Whitelisting to AFD WAF for Defra Networks and Open VPN

.azuredevops/deploy-platform-core-env.yaml, infra/core/env/front-door/adp-portal/front-door-waf.parameters.json
[AB#392325](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/392325)
Fix error while updating the user in portal
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=577624&view=results
- [x ] Story Work items associated (not Tasks)
- [x ] Successful testing run(s) link provided
- [x ] Title pattern should be `{work item number}: {title}`
- [ x] Description covers all the changes in the PR
=> 392325: Unable to Add users to Portal

.azuredevops/deploy-platform-bootstrap-env-shared.yaml, .azuredevops/deploy-platform-core-env.yaml, infra/common/monitoring-insights/monitoring-insights.bicep, infra/common/monitoring-insights/monitoring-insights.bicepparam, infra/core/env/insights/component.bicep, infra/core/env/insights/component.bicepparam
[AB#384866](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/384866) 
Disable Local Auth using avm module.
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=580296&view=results
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=580303&view=results
=> 384866: disablelocalauth

.azuredevops/deploy-platform-core-env.yaml, infra/core/env/front-door/adp-portal/front-door-waf.parameters.json, infra/core/env/front-door/baseline/internal/front-door-waf.parameters.json, infra/core/env/front-door/front-door-waf.bicep
[AB#395100](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/395100)
- Add a ADO Callback custom rule 
- Add a managed exclusion  rule to allow cookies session authentication for coreai-mcu-frontend.snd3.adp.defra.gov.uk 
New custom rule variables are declared in pipeline common
New custom rule and managed rule are in baseline parameter file
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=584184&view=results
- [x ] Story Work items associated (not Tasks)
- [x ] Successful testing run(s) link provided
- [x ] Title pattern should be `{work item number}: {title}`
- [x ] Description covers all the changes in the PR
=> 395100: Add Custom Rule for AllowcallbackAccessRule

.azuredevops/deploy-platform-core-env.yaml, infra/common/network/network-security-group.parameters.json
<!--  Thanks for sending a pull request!  Here are some tips for you:
[AB#397883](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/397883)
Crate a Inbound and Outbound NSG
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=586608&view=results
- [x ] Successful testing run(s) link provided
- [x ] Title pattern should be `{work item number}: {title}`
- [x ] Description covers all the changes in the PR
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.
=> 397883: create inbound and outbound rule for Daisy

infra/core/env/search-service/search-service.bicep
[AB#382093](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/382093)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=590759&view=results
=> 382093: replica count type fix

.azuredevops/deploy-platform-bootstrap-env-shared.yaml, .azuredevops/deploy-platform-bootstrap-env.yaml, .azuredevops/deploy-platform-bootstrap-tenant.yaml, .azuredevops/deploy-platform-build-agent.yaml, .azuredevops/deploy-platform-core-env-shared.yaml, .azuredevops/deploy-platform-core-env.yaml, .azuredevops/deploy-platform-core-iam.yaml, .azuredevops/deploy-platform-core-tenant.yaml, .azuredevops/deploy-platform-kmskeyrotation.yaml, .azuredevops/deploy-platform-sec-env.yaml, .azuredevops/publish-platform-nginxplus.yaml, .azuredevops/publish-powershell-docker-image.yaml, flux-templates/.azuredevops/onboard-new-service.yaml
[AB#407772](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/407772)
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.
=> 407772: Updated service connection

infra/core/env/managed-cluster/aks-cluster.bicep
Update Flux config settings for controllers
[AB#408229](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/408229)
=> 408229:Update Flux config settings

.azuredevops/deploy-platform-bootstrap-tenant.yaml, .azuredevops/deploy-platform-core-iam.yaml, .azuredevops/deploy-platform-core-tenant.yaml, infra/bootstrap/tenant/config/aad-groups/TeamAccessGroups.defra.json, infra/bootstrap/tenant/config/aad-groups/TeamAccessGroups.defradev.json, infra/core/tenant/role-definition/servicebus-data-receive-role.bicep, infra/core/tenant/role-definition/servicebus-data-receive-role.parameters.json
Created Service Bus Access groups for Teams.
Created Service Bus Receive role
Relates to ADO Work Item [AB#409694](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/409694)
=> 409694: Service Bus Access groups for Teams

infra/bootstrap/tenant/config/aad-groups/TeamAccessGroups.defra.json, infra/bootstrap/tenant/config/aad-groups/TeamAccessGroups.defradev.json
Generic Data Reader Writer Access Group
Relates to ADO Work Item [AB#409694](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/409694)
=> 409694: Generic Data Reader Writer Access Group

.azuredevops/deploy-platform-core-env.yaml, infra/core/env/key-vault/application-keyvault-params/key-vault.bicepparam
[AB#419464](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/419464)
Added keyvault secrets officer role to shared connection
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=630266&view=logs&j=3b5a79b6-07d4-5567-40ac-7899972948c5&t=3b5a79b6-07d4-5567-40ac-7899972948c5
=> 419464: ssv service connection keyvault secrets officer role

infra/core/env/front-door/baseline/internal/front-door-waf.parameters.json
Front door WAF policy tuning to support large file upload.
As a part of this tuning, Managed rule 200003 and 200002 are disabled
Relates to ADO Work Item [AB#422083](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/422083)
=> 422083: Front door WAF policy tuning 200003 and 200002 disabled

.azuredevops/deploy-platform-bootstrap-env.yaml, scripts/modules/ado/ado.psm1
[AB#419239](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/419239)
Create Federated Credential in the given app reg
Create federated ADO connection or overwrite the client secret service connection if already exist
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=645584&view=results
=> 419239: Automate Azure DevOps Service Connection Setup with Azure Portal

infra/core/env/managed-cluster/aks-cluster.bicepparam
This PR `ensures system node pools have at least 2 nodes`, improving reliability and preventing cluster failure due to node or hardware issues.
[AB#409139](https://dev.azure.com/defragovuk/DEFRA-FFC/_boards/board/t/DEFRA-FFC%20Team%20Fab/Stories?System.IterationPath=DEFRA-FFC%5CPlatform%5CFab%5CSprint21&workitem=409139)
*Any spe*Any relevant testing information and pipeline runs.*cific actions or notes on review?*
=> 409139: Increase aks system node pool to 2 min nodes 

.azuredevops/deploy-platform-core-env.yaml, infra/common/network/route-table.bicep, infra/common/network/route-table.parameters.json, infra/common/network/virtual-network-flow-logs.bicep, infra/common/network/virtual-network-flow-logs.parameters.json, infra/common/network/virtual-network.bicep, infra/common/network/virtual-network.parameters.json, infra/core/env/postgre-sql/flexible-server.bicep, infra/core/env/postgre-sql/flexible-server.bicepparam
Enable VNet Flow Logs
Update route tables
Enable Postgres Server Logs
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*
https://eaflood.atlassian.net/browse/PL-153
=> Pl153 postgres and routing washup

infra/core/env/ai-document-intelligence/ai-document-intelligence-depolyment-1-params/ai-document-intelligence.parameters.json, infra/core/env/ai-document-intelligence/ai-document-intelligence.bicep
Adding Managed Identity required for DI to access other services
=> Adding User Managed Identity

infra/core/env/ai-document-intelligence/ai-document-intelligence-depolyment-1-params/ai-document-intelligence.parameters.json, infra/core/env/ai-document-intelligence/ai-document-intelligence.bicep
Document Intelligence does not support User Managed Identities. Migrating to System Managed Identities
=> DI does not support User Managed MIs. Moving to System MIs
