DEFRA/adp-infrastructure-core

infra/network/subnet-nsg.parameters.json
Allow all UDP ports inbound traffic within the Virtual network
[AB#165051](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/165051)
=> 165051: Allow Udp Inbound VNET to VNET

.azuredevops/deploy-platform-core.yaml
Removed environments from the pipeline to use the defaults defined in the common pipeline. 
[AB#234076](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/234076)
=> 234076: Use default environments

.azuredevops/deploy-platform-core.yaml, infra/core/managed-cluster/aks-cluster.bicep, infra/core/managed-cluster/aks-cluster.parameters.json
- Added a Postbuild to the Flux Configuration parameters to set variables required by the Flux Kustomizations. These will in future be replaced with Config Maps created as part of the AKS Cluster deployment.
- The SSV5 ACR has anonymous pull, so RBAC is no longer required. I have changed this to instead grant RBAC to the application specific ACR. I have almost modified the pipeline YAML to ensure the AKS Cluster is deployed only after the application ACR has been created.
*Link to the relevant work items: e.g. [AB#244242](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/244242)
=> 244242: Changes to enable Flux to connect to private ACR

infra/core/managed-cluster/.bicep/app-config-data-reader.bicep, infra/core/managed-cluster/aks-cluster.bicep, infra/core/managed-cluster/aks-cluster.parameters.json
We are moving the FluxExtension out of the Cluster deployment to allow us to create a managed identity for app config service after the Cluster deployment.  The Managed Identity requires the cluster_oidc url for Federated Credentials, which can only be obtained after Cluster creation.  The Managed Identity clientId then needs to be passed to the Flux Extension as a postbuild substitute variable.  This will then enable us to create configmaps and secrets using the AzureAppConfigurationProvider.
In addition to the above:
- Created managed identity and federated credential for App Config Service
- Granted App Config Data Reader to the managed identity on the App Config Service
- Remove postbuild substitute variables from parameters file as these will be created via the …
=> 252376: Move flux extension out of AKS deployment

infra/core/managed-cluster/aks-cluster.bicep
The ASO Platform secret values were initially hard-coded to get us moving.  The PR will pass in the required values as postbuild substitution variables.  
The required values are:
- The Platform Team ASO managed identity clientId
- subsciptionId
- tenantId
It made sense to do it this way as these values are available to us in the Bicep template to pass as postbuild substitution variables.  This keeps the solution to not using the hard-code variables simple.
[AB#250536](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/250536)
Discussed solution with Ajay and we both agreed it made sense to do it this way.
Tested in isolated cluster.  Please see screenshot of values coming through on AKS in the Kustomization.
=> Pass variables required by ASO platform secret

infra/core/managed-cluster/aks-cluster.bicep
This change is to align the name change of config-cluster-flux to flux-config.  The change has already been made in adp-flux-core.
[AB#255576](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/255576)
=> 255576: Align flux-config name change as per adp-flux-core and ad-flux-services

.azuredevops/deploy-platform-core-env.yaml
The Azure Monitor Workspace in the Grafana integration is wrong.  This PR will fix it.
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=415824&view=results
=> 273982: Fix Azure monitor workspace id

.azuredevops/deploy-platform-core-env.yaml, infra/core/env/managed-cluster/.bicep/prometheus-logs-requisite-resources.bicep, infra/core/env/managed-cluster/aks-cluster.bicepparam, infra/core/env/observability/dashboards/flux-application-deployments.json, infra/core/env/observability/dashboards/flux-cluster-stats.json, infra/core/env/observability/dashboards/flux-control-plane.json, infra/core/env/observability/grafana.bicep, infra/core/env/observability/grafana.parameters.json, infra/core/env/scripts/New-FluxDashboards.ps1
- Automated adding Flux Dashboards which were previously added manually. The 3 Dashboards are:
1. flux-cluster-stats
2. flux-control-plane
3. GitOps Flux - Application Deployments Dashboard
Reference: https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/monitor-gitops-flux-2
- Granted 'Grafana Admin' permission to the ADO SSV3 (ADO-DefraGovUK-AAD-ADP-SSV3) service principal on the Azure Managed Grafana instance.  This is required to allow the pipeline to create the Dashboards in Grafana
- The PowerShell script will check for existence of the 'Flux' folder and the new dashboards.  If they don't exist they will get created.
- Resolved permissions error which occurred when viewing AppInsights dashboard in Grafana.  This was done by granting 'Reader' permission on the environment …
=> 275548: Add flux dash boards to grafana

infra/core/env/managed-cluster/aks-cluster.bicep
The PRs we raised with Microsoft for adding AzureMonitorProfile ( Prometheus logs ) to the AKS Bicep module and updating the Flux configuration bicep to allow for postbuild variables have been completed and merged into main.
This change will now replace the prerelease versions with the latest version of Bicep modules.
https://github.com/Azure/ResourceModules/pull/4142
https://github.com/Azure/ResourceModules/pull/4331
[AB#277122](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/277122)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=421276&view=logs&s=aee76c8a-1d8b-5149-1924-86de92a850c9
- [] This PR contains documentation
=> 277122: Replace aks and flux bicep module prerelease versions with latest versions

flux-templates/templates/programme/team/service/pre-deploy/environment/image-policy.yaml
All SND pre-deploy image policies are pointing to SND1.  This PR will fix the automation that generates the manifests.
[AB#287810](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/287810)
=> 287810: Fix image policy for flux service pre-deploy

flux-templates/README.md, flux-templates/manifest/full-onboarding-manifest.json, flux-templates/scripts/New-FluxServices.ps1, flux-templates/templates/programme/team/base/patch/kustomize.yaml, flux-templates/templates/programme/team/service/deploy/environment/patch.yaml, flux-templates/templates/programme/team/service/pre-deploy-kustomize.yaml, flux-templates/templates/programme/team/service/pre-deploy/base/kustomization.yaml, flux-templates/templates/programme/team/service/pre-deploy/base/post-migration-script.job.yaml, flux-templates/templates/programme/team/service/pre-deploy/base/pre-migration-script.job.yaml, flux-templates/templates/programme/team/service/pre-deploy/environment/image-policy.yaml, flux-templates/templates/programme/team/service/pre-deploy/environment/kustomization.yaml, flux-templates/templates/programme/team/service/pre-deploy/environment/migration-patch.yaml, flux-templates/templates/programme/team/service/pre-deploy/environment/post-migration-script-patch.yaml, flux-templates/templates/programme/team/service/pre-deploy/environment/pre-migration-script-patch.yaml
This PR contains changes to the Flux Manifest Onboarding Automation to now include files required for Postgres DB Migration.
[AB#267988](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/267988)
[AB#287824](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/287824)
All Flux manifests have successfully reconciled.
=> 267988: Database Permission Management and Migration for PostgresDB Flux Manifests Automation

flux-templates/scripts/New-FluxServices.ps1, flux-templates/templates/environments/environment/kustomization.yaml, flux-templates/templates/environments/environment/ps-exec-image-policy.yaml, flux-templates/templates/programme/team/service/pre-deploy/post-migration/environment/post-migration-script-patch.yaml, flux-templates/templates/programme/team/service/pre-deploy/pre-migration/environment/pre-migration-script-patch.yaml
We noticed the Powershell executor image policy wasn't setup correctly when deployed to DEV environment.  After investigation it was setup at the wrong level which was causing multiple commits by the image automation because environments were conflicting with each other.  The image policy has now been moved into the environment specific folders to resolve the issue.
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*
[AB#292768](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/292768)
[AB#259850](https://dev.azure.com/defragovuk/93c65135-d16b-49d6 …
=> 292768: Add image policy for powershell executor to environment specific folder via automation

flux-templates/templates/programme/team/service/deploy/environment/patch-frontend.yaml, flux-templates/templates/programme/team/service/deploy/environment/patch.yaml, flux-templates/templates/programme/team/service/infra/environment/patch-backend.yaml, flux-templates/templates/programme/team/service/infra/environment/patch.yaml, infra/core/env/app-configuration/config-data/config-data.json
There is a requirement to abstract Memory and CPU Requests/Limits from flux-services into ADP-helm-library.  This change removes the CPU and Memory settings from the patches which are generated by the Onboarding Automation.  This means the values provided by the project team will take affect.  The project team will now be able to select Tiers for CPU and Memory for easier onboarding. 
The change also includes adding the Application KeyVault name to app configuration, so it can be references from the platform config map instead of being hard-coded in the Flux manifests.
[AB#286235](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/286235)
[AB#294359](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/294359)
The changes …
=> 286235: Remove cpu and memory settings from flux patches and add KeyVault to appconfig

.azuredevops/deploy-platform-bootstrap-env.yaml, .azuredevops/deploy-platform-build-agent.yaml
We can't add the PRD stage until we have defined the PRD vars in pipeline common.  As we don't know what some of those values will be yet, we need to remove the PRD stage, so pipelines aren't prevented from running.
[AB#259850](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259850)
[AB#295007](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/295007)
=> 295007: Comment out PRD stages until we have PRD vars ready

.azuredevops/deploy-platform-build-agent.yaml
We can't add the PRE stage until we have deployed dependencies, such as the PRE build agents.  Will uncomment tomorrow once we have dealt with the dependencies.
[AB#259850](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259850)
[AB#295007](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/295007)
=> 295007: Comment out PRE stages until tomorrow as their are dependencies that need to be implemented first

infra/core/env/managed-cluster/.bicep/keyvault-secret-rbac.bicep, infra/core/env/managed-cluster/aks-cluster.bicep, infra/core/env/managed-cluster/aks-cluster.bicepparam
We need to only allow ingress from the AKS Internal LoadBalancer subnet.  This change will pass the AKS ILB Subnet Range to Flux as a post build variable, so we can use it in a Calico Network Policy.
nodeLabels have been removed because we are now using an already available label (**kubernetes.azure.com/mode system**) for both nginx and Calico API server, to ensure pods are only deployed to System nodes.
[AB#248312](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/248312)
Tested against SND1 ensuring Cluster and Applications are still functioning as normal after Network policies have been applied.  We also did additional testing by spinning up pods in application namespaces and ensuring pod to pod communication within the cluster is allowed and …
=> 248312: Implement Azure Kubernetes network policies with Calico

.azuredevops/deploy-platform-core-env.yaml
There is currently a dependency on Production resources (EventHub,KeyVault) being in place to send notifications from Dev, Tst, Pre and Prd Clusters.  This is causing the pipeline platform-adp-core-env pipeline to fail after the Cluster is deployed.
Failure example below
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=522193&view=results
We are temporarily commenting out the section that has dependencies and will revisit this as part of the Flux Notification Stories
[AB#333875](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/333875)
=> 333875: Comment out event-hub-secret-rbac from pipeline

.azuredevops/deploy-platform-core-env.yaml, infra/core/env/scripts/Get-WorkspaceResourceIds.ps1
Fix bug 'Get Azure Monitor Workspace Resource IDs to link to Grafana Dashboard Task failing'
Relates to ADO Work Item [AB#373154](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/373154)
This is an issue with the below Azure Powershell command. This is a quick fix using Azure CLI command.
=> 373154: Fix bug 'Get Azure Monitor Workspace Resource IDs to link to Grafana Dashboard Task failing'

.azuredevops/deploy-platform-core-env.yaml, infra/core/env/app-configuration/config-data/config-data.json, infra/core/env/managed-cluster/aks-cluster.bicepparam
[AB#364244](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/364244)
Add platform variables and value to cluster (ENABLE_PRIVATE_ENDPOINT)
It will remove/restrict to create private end points for the storage accounts in SND environments(DefraDev Tenant).
No manual step required for adding the private IP to the DNS Zone and will not block teams using SND environments
A flag as "enablePrivateEndpoint" is passed from the patch.yaml of each environment (snd,dev, tst, pre and prd).
For SND environment the flag enablePrivateEndpoint is false
For other environments (dev, tst, pre and prd) enablePrivateEndpoint is true
This flag enablePrivateEndpoint being used in adp-aso-helm-library to conditionally create storage accounts with private endpoints.
Any …
=> 364244: Remove Private Endpoints in SND3 Storage Accounts in DEFRA Dev Tenant

.azuredevops/deploy-platform-build-agent.yaml
The build agent service connection name was wrong.  This Pr corrects the name.
[AB#328599](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/328599)
=> 328599: Fix SND4 service connection name

infra/core/env/service-bus/namespace.bicep
[AB#296288](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/296228)
This PR adds support for TLS Version 1.2 for Azure Service Bus.  It upgrades the resource module to get latest api for service bus as namespaces created using api-version prior to 2022-01-01-preview will have 1.0 as the value for MinimumTlsVersion 
=> 296228: Support for TLS Version 1.2 ASB

infra/core/env-shared/flux-notification/config/aad-groups/fluxApiAADGroups.SSV_PRE.json
In order for us to test flux notification and the callback api, we need to have visibility to the flux notifications database in PRE.  This PR will grant the Platform Team reader access to the database.
[AB#353142](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/353142)
=> 353142: Grant read access to Platform team on the flux notifications database in PRE

.azuredevops/deploy-platform-core-env.yaml, infra/core/env/postgre-sql/flexible-server.bicep, infra/core/env/postgre-sql/flexible-server.bicepparam
The postgres user should be different for all environments and not easy to guess.  The usernames for SND1,2 and 3 where previously already set either manually or via automation.  We have decided to leave those as they are for now, so we don't have tear down and rebuid the flexible server.
[AB#383710](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/383710)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=577213&view=logs&s=aee76c8a-1d8b-5149-1924-86de92a850c9
=> 383710: Pass in Postgres admin user from common vars

infra/core/env/managed-cluster/aks-cluster.bicep
AKS ' {env}-cluster-control-plane' and Kubelet identity require the necessary permissions to create and mount persistent volumes such as Azure disks and File Share. 
Contributor permissions at the subscription level will grant access to all teams for their storage accounts hosting the file share or Azure Disk.
Relates to ADO Work Item [AB#383711](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/383711)
=> 383711: Contributor permission to AKS cluster control MI and Kubelet MI

infra/core/env-shared/flux-notification/config/aad-groups/fluxApiAADGroups.SSV_PRD.json
In order to test the Flux Notification solution in Production the ADP Platform team require reader permissions on the Flux Notifications database.  This will also be required for troubleshooting any issues with the Flux Notification in the future.
[AB#390735](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/390735)
=> 390735: Allow ADP Platform engineers  read acces to flux notifications db

infra/core/env/observability/prometheus-alerts.bicepparam
Filter out the KubePodContainerRestart alert for the fluxconfig-agent and fluxconfig-controller pods to reduce noise in the alerting channels.
The fluent-bit container in the fluxconfig-agent and fluxconfig-controller pods is restarting numerous times throughout the day in all environments.  This will result in a lot of alerts which will cause noise and could lead to us missing other alerts.  There is already a bug raised for the fluent-bit container https://github.com/Azure/AKS/issues/4358.  We will also raise a separate ticket with Microsoft in the hope it will speed up a resolution to the pod container restart issue.  We can enable the alert for the fluxconfig-agent and fluxconfig-controller pods once we have a resolution.
[AB#395074](https://dev.azure.com/defragovuk/93c65135-d16b-49d6- …
=> 395074: Filter out fluxconfig-agent and fluxconfig-controller pods for the KubePodContainerRestart alert

infra/core/env/front-door/baseline/internal/front-door-waf.parameters.json
In CoreAI service, Web Application Firewall is blocking a legitimate request and triggering below WAF rules,
MS-ThreatIntel-SQLI-99031002
SQLI-942210
And below details shows it is triggering on diffrent cookie values,
"matchVariableName":"CookieValue:coreai_mcu_frontend_session"
"matchVariableName":"CookieValue:session-auth"
As a generic fix we have tuned WAF exclusion list to exclude Request cookie name contains 'session'
Relates to ADO Work Item [AB#426953](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/426953)
=> 426953: WAF tuning for Request cookie name False positive
